name: subscription_tracker
description: Subscription tracker project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  outline_gradient_button: ^2.0.0+1
  animated_bottom_navigation_bar: ^0.3.3
  dot_navigation_bar: ^1.0.1+4
  dotted_border: ^2.0.0+2
  intl: ^0.17.0
  carousel_slider: ^4.1.1
  currency_text_input_formatter: ^2.1.5
  currency_decimal_formatter: ^0.0.8
  sleek_circular_slider: ^2.0.1
  syncfusion_flutter_gauges: ^20.1.60
  card_swiper: ^2.0.4
  swipe_deck: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
   
  
  